### PR TITLE
feat: upgrade to tauri 2.0

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
Steps taken:
1. install tauri via cargo install tauri-cli
2. see errors when running cargo tauri build
3. run cargo tauri migrate as recommended by docs https://tauri.app/start/migrate/from-tauri-1/
4. manually fix some .ts includes as recommeneded by docs https://tauri.app/start/migrate/from-tauri-1/#migrate-to-core-module
5. successfully build using cargo tauri build

### CODE REVIEW

**Comment by ikatson** [comment]
Oh, wow, thanks for this! I tried recently, failed and gave up to try again sometime later. I think the main reason turned out that v2 wasn't released yet at the time, but it was released 6 hours ago, this is quick! I'll merge once confirmed it works on my system

**Comment by ikatson** [comment]
Seems to work fine so far, thanks again

**Comment by PastaPastaPasta** [comment]
LOL, that's really funny, I didn't realize it was only released so recently! I only saw that I couldn't build and wanted to fix it :)

**Comment by ikatson** [comment]
Ah that explains it! "cargo install tauri-cli" must have installed v2 for you and hence things were broken

**Pull request merged**
